# Generated by Django 4.0.3 on 2022-03-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_comments_user_comments_commented_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commented_user',
            new_name='user',
        ),
    ]
